left_ankle_roll_link:
  pos: [-0.056274279952049255, -0.0147638488560915, -0.0171465165913105]
  quat: [0.9995915293693542, -0.005582260899245739, 0.027340779080986977, 0.006203989032655954]
right_ankle_roll_link:
  pos: [-0.058887895196676254, 0.015732888132333755, -0.016654005274176598]
  quat: [0.9996950030326843, -8.116694516502321e-05, 0.023634763434529305, -0.007147073745727539]
pelvis_contour_link:
  pos: [0.009292741306126118, 0.0066174911335110664, 0.03592683747410774]
  quat: [0.9949902892112732, 0.02084067091345787, 0.014190989546477795, -0.09673941135406494]
torso_link:
  pos: [-0.02534765936434269, -0.0036914360243827105, -0.19408802688121796]
  quat: [0.9998775720596313, -0.009377161972224712, 0.007069930899888277, 0.010335913859307766]
left_rubber_hand:
  pos: [-0.012881291098892689, -0.010380464605987072, 0.0011537119280546904]
  quat: [0.9914815425872803, -0.002342487219721079, 0.11815549433231354, -0.05475533381104469]
right_rubber_hand:
  pos: [-0.012704753316938877, -0.002894774777814746, 0.004582274705171585]
  quat: [0.9942208528518677, 0.03390337899327278, 0.07362369447946548, 0.07039224356412888]
