left_ankle_roll_link:
  pos: [-0.056274279952049255, -0.0147638488560915, -0.0171465165913105]
  quat: [0.9995915293693542, -0.005582260899245739, 0.027340779080986977, 0.006203989032655954]
right_ankle_roll_link:
  pos: [-0.058887895196676254, 0.015732888132333755, -0.016654005274176598]
  quat: [0.9996950030326843, -8.116694516502321e-05, 0.023634763434529305, -0.007147073745727539]
pelvis_contour_link:
  pos: [0.01115097664296627, 0.00034477838198654354, 0.03752546012401581]
  quat: [0.9997531771659851, 0.007130516227334738, 0.020012270659208298, 0.0064953831024467945]
torso_link:
  pos: [-0.039658136665821075, 0.004811773542314768, -0.1869344860315323]
  quat: [0.9984167814254761, 0.0092104971408844, 0.05513134226202965, 0.006285103503614664]
left_rubber_hand:
  pos: [-0.020290473476052284, -0.0031169201247394085, -0.0021871391218155622]
  quat: [0.99530029296875, 0.027475913986563683, 0.0911138728260994, 0.01790580339729786]
right_rubber_hand:
  pos: [-0.02310660108923912, 0.005914268549531698, 0.005707487463951111]
  quat: [0.9966209530830383, 0.019418545067310333, 0.07955057919025421, -0.006423263810575008]
