left_ankle_roll_link:
  pos: [-0.056274279952049255, -0.0147638488560915, -0.0171465165913105]
  quat: [0.9995915293693542, -0.005582260899245739, 0.027340779080986977, 0.006203989032655954]
right_ankle_roll_link:
  pos: [-0.058887895196676254, 0.015732888132333755, -0.016654005274176598]
  quat: [0.9996950030326843, -8.116694516502321e-05, 0.023634763434529305, -0.007147073745727539]
pelvis_contour_link:
  pos: [0.006214044522494078, 0.005215427838265896, 0.037680305540561676]
  quat: [0.9971880912780762, 0.0164901465177536, 0.024900000542402267, -0.06873168051242828]
torso_link:
  pos: [-0.02565414272248745, -1.6539052012376487e-06, -0.19160036742687225]
  quat: [0.999768853187561, -0.00489606149494648, 0.008149083703756332, 0.01928417943418026]
left_rubber_hand:
  pos: [-0.016769178211688995, -0.00597105547785759, -0.0011903693666681647]
  quat: [0.9861802458763123, -0.04226209223270416, 0.14724156260490417, -0.06310571730136871]
right_rubber_hand:
  pos: [-0.014562956057488918, -0.004048321861773729, 0.00031877780565992]
  quat: [0.993918776512146, 0.049963656812906265, 0.06662006676197052, 0.07204834371805191]
