pelvis_contour_link:
  pos: [0.0, 0.0, 0.0]
  quat: [1.0, 0.0, 0.0, 0.0]
torso_link:
  pos: [0.0, 0.0, 0.0]
  quat: [1.0, 0.0, 0.0, 0.0]
left_rubber_hand:
  pos: [0.0, 0.0, 0.0]
  quat: [1.0, 0.0, 0.0, 0.0]
right_rubber_hand:
  pos: [0.0, 0.0, 0.0]
  quat: [1.0, 0.0, 0.0, 0.0]
left_ankle_roll_link:
  pos: [0.0, 0.0, 0.0]
  quat: [1.0, 0.0, 0.0, 0.0]
right_ankle_roll_link:
  pos: [0.0, 0.0, 0.0]
  quat: [1.0, 0.0, 0.0, 0.0]
