left_ankle_roll_link:
  pos: [-0.056274279952049255, -0.0147638488560915, -0.0171465165913105]
  quat: [0.9995915293693542, -0.005582260899245739, 0.027340779080986977, 0.006203989032655954]
right_ankle_roll_link:
  pos: [-0.058887895196676254, 0.015732888132333755, -0.016654005274176598]
  quat: [0.9996950030326843, -8.116694516502321e-05, 0.023634763434529305, -0.007147073745727539]
