left_hip_pitch_joint: -0.04663645103573799
left_hip_roll_joint: 0.005365275777876377
left_hip_yaw_joint: -0.015837091952562332
left_knee_joint: -0.008389001712203026
left_ankle_pitch_joint: 0.01876944676041603
left_ankle_roll_joint: -0.03239918127655983
right_hip_pitch_joint: -0.026009907945990562
right_hip_roll_joint: -0.006931017152965069
right_hip_yaw_joint: 0.020803770050406456
right_knee_joint: 0.0021683527156710625
right_ankle_pitch_joint: 0.032917674630880356
right_ankle_roll_joint: -0.008786087855696678
waist_yaw_joint: -0.0004692617803812027
waist_roll_joint: -0.0010239077964797616
waist_pitch_joint: -0.015827497467398643
left_shoulder_pitch_joint: -0.004462325479835272
left_shoulder_roll_joint: 0.0087732570245862
left_shoulder_yaw_joint: -0.01690378226339817
left_elbow_joint: 0.014319413341581821
left_wrist_roll_joint: -0.0036727662663906813
left_wrist_pitch_joint: 0.021622955799102783
left_wrist_yaw_joint: -0.0031678529921919107
right_shoulder_pitch_joint: 0.020237285643815994
right_shoulder_roll_joint: -0.0322483666241169
right_shoulder_yaw_joint: -0.012252885848283768
right_elbow_joint: 0.034452036023139954
right_wrist_roll_joint: 0.0027614356949925423
right_wrist_pitch_joint: 0.010605882853269577
right_wrist_yaw_joint: -0.004728345200419426
