left_hip_pitch_joint: -0.004640543833374977
left_hip_roll_joint: -0.0035843004006892443
left_hip_yaw_joint: -0.0012698156060650945
left_knee_joint: 0.00038246726035140455
left_ankle_pitch_joint: 0.004193094093352556
left_ankle_roll_joint: -0.023258253931999207
right_hip_pitch_joint: -0.0022133460734039545
right_hip_roll_joint: -0.0010201050899922848
right_hip_yaw_joint: 0.0014375026803463697
right_knee_joint: 0.008662892505526543
right_ankle_pitch_joint: 0.018894637003540993
right_ankle_roll_joint: -0.0028187851421535015
waist_yaw_joint: -0.00020843782112933695
waist_roll_joint: -0.0004903653170913458
waist_pitch_joint: -0.0007096935296431184
left_shoulder_pitch_joint: -0.0006896690465509892
left_shoulder_roll_joint: 0.003776779631152749
left_shoulder_yaw_joint: -5.674465501215309e-05
left_elbow_joint: 0.001433825003914535
left_wrist_roll_joint: -0.0005156745319254696
left_wrist_pitch_joint: 0.002683615544810891
left_wrist_yaw_joint: 7.6084324973635375e-06
right_shoulder_pitch_joint: 0.012110857293009758
right_shoulder_roll_joint: -0.010990718379616737
right_shoulder_yaw_joint: -0.004038253333419561
right_elbow_joint: 0.006019773427397013
right_wrist_roll_joint: 0.0004254635132383555
right_wrist_pitch_joint: 0.002258055377751589
right_wrist_yaw_joint: -0.00119636463932693
