left_hip_pitch_joint: 0.006870078854262829
left_hip_roll_joint: 0.012398198246955872
left_hip_yaw_joint: -0.002682953607290983
left_knee_joint: -0.06780312210321426
left_ankle_pitch_joint: 0.04910606890916824
left_ankle_roll_joint: -0.038110628724098206
right_hip_pitch_joint: 0.003977313172072172
right_hip_roll_joint: 0.01388937421143055
right_hip_yaw_joint: 0.006738940253853798
right_knee_joint: -0.030321061611175537
right_ankle_pitch_joint: 0.045046139508485794
right_ankle_roll_joint: -0.004176840651780367
waist_yaw_joint: -0.0033142343163490295
waist_roll_joint: 0.010389530099928379
waist_pitch_joint: 0.010289722122251987
left_shoulder_pitch_joint: -0.044708628207445145
left_shoulder_roll_joint: 0.007444169372320175
left_shoulder_yaw_joint: 0.01440404448658228
left_elbow_joint: 0.010299730114638805
left_wrist_roll_joint: -0.005768452305346727
left_wrist_pitch_joint: 0.0002216008579125628
left_wrist_yaw_joint: -0.0018868318293243647
right_shoulder_pitch_joint: -0.03696218132972717
right_shoulder_roll_joint: -0.007910664193332195
right_shoulder_yaw_joint: -0.01783856935799122
right_elbow_joint: -0.07474812120199203
right_wrist_roll_joint: -0.01006636954843998
right_wrist_pitch_joint: 0.0626714676618576
right_wrist_yaw_joint: 0.004941998049616814
