left_hip_pitch_joint: 0.0
left_hip_roll_joint: 0.0
left_hip_yaw_joint: 0.0
left_knee_joint: 0.0
left_ankle_pitch_joint: 0.0
left_ankle_roll_joint: 0.0
right_hip_pitch_joint: 0.0
right_hip_roll_joint: 0.0
right_hip_yaw_joint: 0.0
right_knee_joint: 0.0
right_ankle_pitch_joint: 0.0
right_ankle_roll_joint: 0.0
waist_yaw_joint: 0.0
waist_roll_joint: 0.0
waist_pitch_joint: 0.0
left_shoulder_pitch_joint: 0.0
left_shoulder_roll_joint: 0.0
left_shoulder_yaw_joint: 0.0
left_elbow_joint: 0.0
left_wrist_roll_joint: 0.0
left_wrist_pitch_joint: 0.0
left_wrist_yaw_joint: 0.0
right_shoulder_pitch_joint: 0.0
right_shoulder_roll_joint: 0.0
right_shoulder_yaw_joint: 0.0
right_elbow_joint: 0.0
right_wrist_roll_joint: 0.0
right_wrist_pitch_joint: 0.0
right_wrist_yaw_joint: 0.0
